### ISSUE TITLE
Problem compiling murax demo with gcc 7.1.1

### ISSUE THREAD

**Issue by impostask** [SpinalHDL/VexRiscvSocSoftware#1]
I couldn't compile murax demo, murax dhrystone is ok.

The error message is:

/tmp/VexRiscvSocSoftware/projects/murax/demo/src/crt.S:74:(.text+0xf0): relocation truncated to fit: R_RISCV_PCREL_LO12_I against `.L0 '

The interesting part is that although the error message points to crt.S, even if i copy the crt.S from dhrystone, the error persists.

RISC-V Gnu toolchain compiled as suggested (rv32im and rv322i).

**Comment by Dolu1990** [comment]
It's weird, because for me it's working fine (i just tested now)

Any way, i just changed the GCC requirements in this commit : (https://github.com/SpinalHDL/VexRiscvSocSoftware/commit/9884feda587b52248908cb13e5ea5fc9b27e63ca)

Now you need to use the  prebuild SiFive GNU Embedded  from https://www.sifive.com/products/tools/ 
It should be place in /opt/rv/

Then everything should be fine : D

Let's me know

**Comment by Dolu1990** [comment]
Sorry,  not /opt/rv/   but /opt/riscv/

**Comment by impostask** [comment]
It is working with sifive toolchain.
